### PR TITLE
Fix select creation in RvsdgToIpGraphConverter

### LINKED ISSUE #846: Assert fails when compiling simple switch with char*
The following C code:

```c
const char* func(int colorid)
{
	const char *cp = "a";
	switch (colorid) {
		case 1:
			cp = "b"; break;
	}

	return cp;
}
```

when compiled with
```c
clang -Xclang -disable-O0-optnone -S -emit-llvm -c test.c -o test.ll
opt -passes=mem2reg test.ll -S -o test-m2r.ll
jlm-opt test-m2r.ll -o test-jlm-opt.ll
```

fails during `jlm-opt` with the error:
```
Type error - expected : bit32, received : bit1
```

Interestingly, it does not fail if the `const char*` is replaced by an `int`.

### PR DESCRIPTION
**Pull request by phate**
The RvsdgToIpGraphConverter was not handling the conversion of empty gamma nodes with match nodes to select operations correctly. This PR fixes the problems with it by creating select predicate operations in case there is no identity mapping in the match operation.

Close #846

### CODE REVIEW

File: jlm/llvm/backend/RvsdgToIpGraphConverter.cpp [hunk 1]
```diff
@@ -277,25 +278,58 @@ RvsdgToIpGraphConverter::ConvertEmptyGammaNode(const rvsdg::GammaNode & gammaNod
...
+        // 2. 1 -> 1, default 0
+        // There is no need to insert operations for the select predicate
+        selectPredicate = matchOrigin;
+        trueAlternative = Context_->GetVariable(output1);
+        falseAlternative = Context_->GetVariable(output0);
+      }
+      else
+      {
+        // FIXME: This will recreate the select predicate operations for each gamma output for
+        // which we create a select.
```
Comment (phate) [inline jlm/llvm/backend/RvsdgToIpGraphConverter.cpp:311]: Please ignore this for now. My plan is to move the entire select creation out of the RvsdgToIpGraph convert into its own transformation pass, and invoke as one of the last passes in the optimization pipeline. The entire IfConversion story of gamma nodes does not really belong in the RvsdgToIpGraph converter.

The FIXME will be handled once this is done.

File: jlm/llvm/backend/RvsdgToIpGraphConverter.cpp [hunk 2]
```diff
@@ -277,25 +278,58 @@ RvsdgToIpGraphConverter::ConvertEmptyGammaNode(const rvsdg::GammaNode & gammaNod
...
-      const auto matchOperation = util::AssertedCast<const rvsdg::match_op>(&node->GetOperation());
-      const auto defaultAlternative = matchOperation->default_alternative();
-      const auto condition = Context_->GetVariable(node->input(0)->origin());
-      const auto trueAlternative =
-          defaultAlternative == 0 ? Context_->GetVariable(output1) : Context_->GetVariable(output0);
-      const auto falseAlternative =
-          defaultAlternative == 0 ? Context_->GetVariable(output0) : Context_->GetVariable(output1);
+      const auto matchOperation =
+          util::AssertedCast<const rvsdg::match_op>(&matchNode->GetOperation());
+      assert(matchOperation->nalternatives() == 2);
```
Comment (haved) [inline jlm/llvm/backend/RvsdgToIpGraphConverter.cpp:286]: Is there a reason for using assert and not `JLM_ASSERT`?

File: jlm/llvm/backend/RvsdgToIpGraphConverter.cpp [hunk 3]
```diff
@@ -277,25 +278,58 @@ RvsdgToIpGraphConverter::ConvertEmptyGammaNode(const rvsdg::GammaNode & gammaNod
...
+
+      const auto matchOrigin = Context_->GetVariable(matchNode->input(0)->origin());
+      const auto caseValue = matchOperation->begin()->first;
+      const auto caseSubregion = matchOperation->begin()->second;
```
Comment (haved) [inline jlm/llvm/backend/RvsdgToIpGraphConverter.cpp:290]: At this point we have asserted that the match only has two alternatives, but does that necessarily mean that it only has one (value->alt) mapping, and one default alternative? If it has multiple mapping then we might not be able to convert it into a select, but has that case been determined to never occur before reaching this point in the code?

**Review by haved — COMMENTED** [review]
Some quick comments for now, will look more

File: jlm/llvm/backend/RvsdgToIpGraphConverter.cpp (hunk 3 above)
Comment (phate) [reply jlm/llvm/backend/RvsdgToIpGraphConverter.cpp:290]: It should, but the input from the match operation is not really well checked (to put it nicely). We should improve this. I put another `JLM_ASSERT()` there that ensures that we really have only two cases. At least, it will scream at us when this is not the case.

**Comment by phate** [comment]
@haved I believe to have addressed your comments.

**Review by haved — APPROVED** [review]
Looks good, I thought for a second I saw something more, but I did not consider that the match [1->0] default 1 is actually a bit more tricky than just swapping true and false (consider what happens if the input is 2)
